### ISSUE TITLE
Local storage be full

### ISSUE THREAD

**Issue by thanhnguyentps** [Nolanus/ngx-multi-window#24]
How can I remove the message with status 'read', please let me know

**Comment by Nolanus** [comment]
Hi @thanhnguyentps,
I'm not quite sure whether I get what you're asking for. The size limit for the local storage is a few megabyte (https://stackoverflow.com/questions/2989284/what-is-the-max-size-of-localstorage-values), so it should be more than enough for sending basic messages and some more complex data structures.

The message that is "send" to the window that sent the initial message in order to inform it about a successful processing, will be removed automatically as soon as the initial message is removed from the windows outbox. Please refer to the [Communication strategy section of the readme](https://github.com/Nolanus/ngx-multi-window#communication-strategy) for an example how the communication works. There's no need to manually remove messages.
