### ISSUE TITLE
Not an issue however I have a question on why messageTimeOut is set to 10 seconds

### ISSUE THREAD

**Issue by SimonJChen** [Nolanus/ngx-multi-window#93]
Hey, as stated in the title, I'm wondering why the message time out is set to 10 seconds and not longer. What would the drawbacks be if it were set to a longer frame?

Thanks

**Comment by Nolanus** [comment]
Hi @SimonJChen,

sure! From technical perspective, the longer the `messageTimout` the longer messages destined for a possible stalled or closed window will remain in the `outbox`. All `outbox`es are parsed every `heartbeat`-seconds (defaults to 1s) by all open windows. The larger the `outbox` to be parsed and inspected, the longer this processing takes it'll block the event loop. However, it highly depends on the number and size of messages you are sending around.

Another consideration is depending on your business logic: for how long is receiving a message that old still relevant? Given that your application synchronizes it's state to other windows every `x´ seconds, keeping messages older than `x` seconds probably not make sense anyway, as a never message about the latest state has been pushed to the `outbox` in the meantime.

The last reason is about probability: if a window has not received a message after 10 seconds, what is the probability that it is still alive? You can keep waiting, but at some point the resources should be released. Whether 10000ms is the ideal value is not statistically proven or something like that ;)

Sebastian

**Comment by JaredScar** [comment]
Hey Sebastion (@Nolanus),

I seem to have found an issue with this code. Not sure if it's an issue or maybe intended on how it works. It seems when sending a message whilst the messages are still being processed, sometimes not all the windows are gathered. Also, all the undocked windows seem to read the messages 1 by 1 in the order they get sent to each window. For example, if I send 500 messages to window `B` from window `A`. If I send 500 messages from window `A` to window `C`. Window `C` will wait until all the messages to window `B` are processed before it starts processing it's messages...

This is an issue considering if someone wants to send the messages to all windows, this would be quite an issue if they relied on the `getKnownWindows()` function in your codebase.

Thanks.

Best Regards,
Jared

**Comment by JaredScar** [comment]
![image](https://github.com/Nolanus/ngx-multi-window/assets/8027457/9bce4585-0462-418a-8df8-b6d6ace0b5a1)

After further investigation and debugging... It seems to be the code that handles the window timeout. The issue with this code is that the window isn't actually timing out, but taking a long time to process all the messages it has to go through. If I remove this code, the knownWindows always seems to be correct.

Because of this, I propose that the timeout code be removed as it seems to be a detriment to the library rather than properly working. Maybe the unload event of the window should handle the removal of it's local storage instead of a timeout? Just an idea.

**Comment by Nolanus** [comment]
Hi @JaredScar,

thanks for the examples and insights. Sending 500 messages to all open windows is definitely a large number, not speaking of the 5000 used in your example code. Sending hundred or thousands of messages accross windows on a regular basis is a scale that has not been considered necessary when I designed the library.

However, the window scanning and stalling detection works as expected: when a window is not "responding" for a given time, it is considered stalled. The reason for the window not responding does not matter and cannot be accurately determined from other windows. It can perfectly happen that processing received messages takes a while and blocks the target window's event loop, resulting it the window not responding (to any user input nor updating the data in the localstorage for cross-window communication). Using the [`unload` event is unreliable](https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event#usage_notes) and thus unfortunately not a viable solution.

If an application has a scenario with loads of messages, increasing the timeout is a possible option and one of the reasons the `windowTimeout` config can be adjusted. This can prevent that a window is considered unresponsive and removed from the list of known windows too early. Note though, that once the window becomes responsive again, it is added back to the `knowWindows` again. Depending on the application use case this might be acceptable.

I do agree that the Broadcastchannel API is way better suited for that use case... it's actually specifically made for this. The localstorage method is just [one way to accomplish that](https://stackoverflow.com/questions/28230845/communication-between-tabs-or-windows) and had better browser support back in 2017. Luckily, [Broadcastchannel API browser support has increased](https://caniuse.com/broadcastchannel) dramatically since than. Big thanks for the PR on that!
